precompile(Ipopt.eval_jac_g_wrapper, (Int32, Ptr{Float64}, Int32, Int32, Int32, Ptr{Int32}, Ptr{Int32}, Ptr{Float64}, Ptr{Void},))
precompile(Ipopt.eval_h_wrapper, (Int32, Ptr{Float64}, Int32, Float64, Int32, Ptr{Float64}, Int32, Int32, Ptr{Int32}, Ptr{Int32}, Ptr{Float64}, Ptr{Void},))
precompile(Ipopt.createProblem, (Int64, Array{Float64, 1}, Array{Float64, 1}, Int64, Array{Float64, 1}, Array{Float64, 1}, Int64, Int64, Function, Function, Function, Function, Function,))
precompile(Ipopt.eval_f_wrapper, (Int32, Ptr{Float64}, Int32, Ptr{Float64}, Ptr{Void},))
precompile(Ipopt.eval_g_wrapper, (Int32, Ptr{Float64}, Int32, Int32, Ptr{Float64}, Ptr{Void},))
precompile(Ipopt.eval_grad_f_wrapper, (Int32, Ptr{Float64}, Int32, Ptr{Float64}, Ptr{Void},))
precompile(Ipopt.call, (Type{Ipopt.IpoptProblem}, Ptr{Void}, Int64, Int64, Function, Function, Function, Function, Function,))
precompile(Ipopt.call, (Array{Any, 1}, Type{Ipopt.IpoptMathProgModel},))
precompile(Ipopt.optimize!, (Ipopt.IpoptMathProgModel,))
precompile(Ipopt.call, (Array{Any, 1}, Type{Ipopt.IpoptSolver},))
precompile(Ipopt.addOption, (Ipopt.IpoptProblem, ASCIIString, ASCIIString,))
precompile(Ipopt.NonlinearModel, (Ipopt.IpoptSolver,))
precompile(Ipopt.status, (Ipopt.IpoptMathProgModel,))
precompile(Ipopt.solveProblem, (Ipopt.IpoptProblem,))
precompile(Ipopt.call, (Type{Ipopt.IpoptMathProgModel},))
precompile(Ipopt.addOption, (Ipopt.IpoptProblem, ASCIIString, Int64,))
precompile(Ipopt.getobjval, (Ipopt.IpoptMathProgModel,))
precompile(Ipopt.setwarmstart!, (Ipopt.IpoptMathProgModel, Array{Float64, 1},))
precompile(Ipopt.getsolution, (Ipopt.IpoptMathProgModel,))
